### ISSUE TITLE
Calico-vpp-node agent restarts

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#329]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2
- Kubernetes version: v1.21.1
- kind cluster

**Issue description**
Sometimes I see calico-vpp-nodes restarts.
Logs:
```
...
time="2022-02-14T11:12:20Z" level=info msg="Main client watcher loop"
time="2022-02-14T11:13:28Z" level=info msg="Terminating main client watcher loop"
time="2022-02-14T11:13:41Z" level=info msg="Terminating main client watcher loop"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b8b84a]

goroutine 47 [running]:
github.com/projectcalico/vpp-dataplane/calico-vpp-agent/watchers.nodeSpecCopy(0x0, 0xc000ceedd8)
	/home/nskrzypc/vpp-dataplane/calico-vpp-agent/watchers/nodes_watcher.go:50 +0x6a
github.com/projectcalico/vpp-dataplane/calico-vpp-agent/watchers.(*NodeWatcher).WatchNodes(0xc00005d080, 0x347c120, 0x0, 0x0)
	/home/nskrzypc/vpp-dataplane/calico-vpp-agent/watchers/nodes_watcher.go:120 +0x19c
main.Go.func1(0x0, 0x0)
	/home/nskrzypc/vpp-dataplane/calico-vpp-agent/cmd/calico_vpp_dataplane.go:69 +0x35
gopkg.in/tomb%2ev2.(*Tomb).run(0x347c120, 0xc000a937c0)
	/home/nskrzypc/.go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x38
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/nskrzypc/.go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xbc
```

**Steps**
1. Start Calico-VPP on kind cluster
2. Wait 30-60 minutes
3. `kubectl get pods --all-namespaces`
4. See restarts
```
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE
calico-vpp-dataplane   calico-vpp-node-bklxg                        2/2     Running   1          68m
calico-vpp-dataplane   calico-vpp-node-pj8zt                        2/2     Running   1          69m
calico-vpp-dataplane   calico-vpp-node-wmtxr                        2/2     Running   1          68m
kube-system            calico-kube-controllers-6b9fbfff44-rwkps     1/1     Running   0          7h18m
...
```
Full log:
[calico_vpp_agent_log.txt](https://github.com/projectcalico/vpp-dataplane/files/8060345/calico_vpp_agent_log.txt)

**Comment by sknat** [comment]
Hi @glazychev-art 
Thanks for the report !
This issue should be covered by #298 before, we were indeed not handling the channel closing
correctly, and we could end up with node being nil

You can test with the `:latest` images which should contain this fix

**Comment by glazychev-art** [comment]
@sknat 
Thank you!

**Comment by glazychev-art** [comment]
I think we can close this issue, I haven't seen this issue again. Thanks!
